swagger: '2.0'
info:
  title: NativeSync API - plexsystems calls
  description: plexsystems calls within NativeAPI
  version: "1.0.0"
  x-service-label: Plex Systems ERP
  x-service-name: plexsystems
  x-credentials-type: keys
  x-credentials-template:
      - label: Username
        system_name: username
        type: string
      - label: Password
        system_name: password
        type: string
      - label: Use Test API?
        system_name: use_test_api
        type: boolean

# the domain of the service
host: api.nativesync.io
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /v1/plexsystems
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  APIKey:
    type: apiKey
    name: x-api-key
    in: header
paths:
  /add_ecommerce_order:
    post:
      security:
        - APIKey: []
      summary: Add Ecommerce Order
      description: "Adds an ecommerce order to plex"
      parameters:
        - name: credentials_name
          in: query
          description: Optional name of the credentials to use with this request
          required: false
          type: string
        - name: input
          in: body
          description: Input to API
          required: true
          schema:
            type: 
            $ref: '#/definitions/add_ecommerce_order_input'
      responses:
        200:
          description: API call results
          schema:
            $ref: '#/definitions/add_ecommerce_order_output'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/error'
  /add_ecommerce_order_line:
    post:
      security:
        - APIKey: []
      summary: Adds an Ecommerce Order Line
      description: "Adds a line to an existing Ecommerce Order"
      parameters:
        - name: credentials_name
          in: query
          description: Optional name of the credentials to use with this request
          required: false
          type: string
        - name: input
          in: body
          description: Input to API
          required: true
          schema:
            type: 
            $ref: '#/definitions/add_ecommerce_order_line_input'
      responses:
        200:
          description: API call results
          schema:
            $ref: '#/definitions/add_ecommerce_order_line_output'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/error'
definitions:
  add_ecommerce_order_input:
    type: object
    required:
      - customer_code
      - ship_to_customer_address_code
      - bill_to_customer_address_code
    properties:
      customer_code:
        type: string
      ship_to_customer_address_code:
        type: string
      bill_to_customer_address_code:
        type: string
  add_ecommerce_order_line_input:
    type: object
    required:
      - customer_code
      - order_no
      - part_no
      - price
      - quantity
    properties:
      customer_code:
        type: string
      order_no:
        type: string
      part_no:
        type: string
      price:
        type: number
      quantity:
        type: integer
  add_ecommerce_order_output:
    type: object
    required:
      - order_no
      - result_code
      - result_message
      - result_error
    properties:
      order_no:
        type: string
      result_code:
        type: integer
      result_message:
        type: string
      result_error:
        type: boolean
  add_ecommerce_order_line_output:
    type: object
    required:
      - result_code
      - result_message
      - result_error
    properties:
      result_code:
        type: integer
      result_message:
        type: string
      result_error:
        type: boolean
  error:
    type: string

