swagger: '2.0'
info:
  title: NativeSync API - System calls
  description: System calls within NativeAPI
  version: "1.0.0"
  x-service-name: System
  x-service-system-name: system
  x-connector-name: System
  x-credentials-type: none
  x-credentials-template:

# the domain of the service
host: api.nativesync.io
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /api/v1/system
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  APIKey:
    type: apiKey
    name: apikey
    in: header
paths:
  /debug_value:
    post:
      security:
        - APIKey: []
      summary: Debug a value
      description: "Returns the value specified in the POST body"
      parameters:
        - name: credential_name
          in: query
          description: Optional name of the credentials to use with this request
          required: false
          type: string
        - name: input
          in: body
          description: Input to API
          required: true
          schema:
            $ref: '#/definitions/debug_value_input'
      responses:
        200:
          description: API call results
          schema:
            $ref: '#/definitions/debug_value_output'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/error'
  /custom_trigger:
    post:
      security:
        - APIKey: []
      summary: Triggers an integration
      description: "Triggers an integration"
      parameters:
        - name: credential_name
          in: query
          description: Optional name of the credentials to use with this request
          required: false
          type: string
        - name: input
          in: body
          description: Input to API
          required: true
          schema:
            $ref: '#/definitions/custom_trigger_input'
      responses:
        200:
          description: API call results
          schema:
            $ref: '#/definitions/custom_trigger_output'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/error'
definitions:
  debug_value_input:
    type: object
  debug_value_output:
    type: object
  custom_trigger_input:
    type: object
    properties:
      integration_id:
        type: integer
      trigger_data:
        type: object
  custom_trigger_output:
    type: object
    properties:
      result:
        type: object
  error:
    type: string

